### ISSUE TITLE
error while running setup.py

### ISSUE THREAD

**Issue by minipapergarden** [Vedant-Bhalgama/Avyukt#6]
`   / \__   ___   _ _   _| | _| |_  / ___|  ___| |_ _   _ _ __
  / _ \ \ / / | | | | | | |/ / __| \___ \ / _ \ __| | | | '_ \
 / ___ \ V /| |_| | |_| |   <| |_   ___) |  __/ |_| |_| | |_) |
/_/   \_\_/  \__, |\__,_|_|\_\\__| |____/ \___|\__|\__,_| .__/
             |___/                                      |_|

[+] Setup File Version 1.0 (Beta)

[+] Setup Build Date : 23/8/2020

[+] Detected OS : Linux

[+] OS Release : 4.19.0-14-amd64

[+] Starting Setup, Please wait ...
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    setup()
  File "setup.py", line 22, in setup
    start_installation = raw_input("\nAvyukt>: Type y if you want to start installation else n >> ")
NameError: name 'raw_input' is not defined
root@root:~/Avyukt/Avyukt_Setup#
`

**Comment by Vedant-Bhalgama** [comment]
Are you running it with Python3?

**Comment by muratberisha98** [comment]
Yes
